apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: frontend
  name: frontend-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-con
        image: redis:alpine
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "http://35.203.58.230:3550/"
          - name: SHIPPING_SERVICE_ADDR
            value: "http://35.203.58.230:50051/"
          - name: CHECKOUT_SERVICE_ADDR
            value: "http://35.203.58.230:5050/"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "http://35.203.58.230:5000/"
          - name: CURRENCY_SERVICE_ADDR
            value: "http://35.203.58.230:7000/"
          - name: CART_SERVICE_ADDR
            value: "http://35.203.58.230:7070/"
          - name: AD_SERVICE_ADDR
            value: "http://35.203.58.230:9555/"

#           - name: PRODUCT_CATALOG_SERVICE_ADDR
#             value: "http://catalog-svc:3550"
#           - name: SHIPPING_SERVICE_ADDR
#             value: "http://shipping:50051"
#           - name: CHECKOUT_SERVICE_ADDR
#             value: "http://checkout-svc:5050"
#           - name: RECOMMENDATION_SERVICE_ADDR
#             value: "http://recommendation:5000"
#           - name: CURRENCY_SERVICE_ADDR
#             value: "http://currency:7000"
#           - name: CART_SERVICE_ADDR
#             value: "http://cartservice-svc:7070"
#           - name: AD_SERVICE_ADDR
#             value: "http://adservice-svc:9555"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
